name: demo-hls-stream

services:
  hls-server:
    build: ./services/hls-server
    image: hls-server
    ports:
      - 80:80
    volumes:
      - hls:/tmp/hls
    networks:
      - my-network
    depends_on:
      - rtmp-server

  rtmp-server:
    build: ./services/rtmp-server
    image: rtmp-server
    ports:
      - 1935:1935
    networks:
      - my-network

volumes:
  hls:

networks:
  my-network:
    driver: bridge
