name: demo-hls-stream

services:
  ws-server:
    build: ./services/ws-server
    image: ws-server
    ports:
      - 3000:3000
  rtmp-server:
    build: ./services/rtmp-server
    image: rtmp-server
    ports:
      - 1935:1935
      - 80:80
    volumes:
      - hls:/tmp/hls

volumes:
  hls:
