name: demo-hls-stream

services:
  hls-server:
    container_name: hls-server
    build: ./services/hls-server
    image: hls-server
    ports:
      - 8080:80
    expose:
      - 1935
    networks:
      - my-network

  rtmp-server:
    container_name: rtmp-server
    build: ./services/rtmp-server
    image: rtmp-server
    ports:
      - 1935:1935
    expose:
      - 1935
    networks:
      - my-network
    depends_on:
      - hls-server

  ws-server:
    container_name: ws-server
    build: ./services/ws-server
    image: ws-server
    ports:
      - 3000:3000
    networks:
      - my-network
    depends_on:
      - rtmp-server

networks:
  my-network:
    driver: bridge
